trigger:
  batch: true
  branches:
    include:
    - master
    - releases/*
    - features/*
  paths:
    exclude: [ 'README.md' ]

pool:
  vmImage: ubuntu-latest
  timeoutInMinutes:

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: 3.10
- script: |
    set -e
    python3 -m pip install wheel
    python3 -m pip install pytest pytest-cov
    python3 -m pip install -r conduit_raw/requirements.txt
    python3 -m pip install -r conduit_index/requirements.txt
  displayName: 'Install ConduitDB dependencies'
- script: |
    set -e
    python3 -m pip install -U pylint
    python3 -m pylint --rcfile ./.pylintrc ./conduit_raw ./conduit_index ./conduit_lib
    if [ $? -gt 0 ]
    then
      # https://docs.pylint.org/en/1.6.0/run.html#exit-codes
      echo "##vso[task.complete result=Failed;]DONE"
    fi
  continueOnError: true
  displayName: 'Pylint'

- script: |
    python3 -m pip install mypy
    yes | python3 -m mypy --install-types
    python3 -m mypy --config-file mypy.ini ./conduit_raw --python-version 3.10
    python3 -m mypy --config-file mypy.ini ./conduit_lib --python-version 3.10
    python3 -m mypy --config-file mypy.ini ./conduit_index --python-version 3.10
  continueOnError: true
  displayName: 'Mypy static analysis'

- script: |
    docker-compose -f docker-compose.yml build --parallel
    docker-compose -f docker-compose.yml up --detach
    sleep 15
    docker-compose -f docker-compose.yml logs
  timeoutInMinutes: 10
  continueOnError: true
  displayName: 'Run dockerized services'

- script: |
    pytest tests --verbose
    pytest tests_functional --verbose || docker-compose -f docker-compose.yml logs
  timeoutInMinutes: 10
  continueOnError: true
  displayName: 'Pytest'

- script: |
    docker-compose -f docker-compose.yml down
  timeoutInMinutes: 10
  continueOnError: true
  displayName: 'Docker Down'
