version: "3.8"

services:

#  zookeeper:
#    image: zookeeper:3.4.14
#    expose:
#      - "2181"
#
#  kafka:
#    image: wurstmeister/kafka:2.13-2.6.0
#    hostname: kafka
#    ports:
#      - "26638:26638"
#    depends_on:
#      - zookeeper
#    environment:
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:26638
#      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:26638
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_CREATE_TOPICS: "conduit-raw-headers-state:1:1,mempool-txs:6:1"
#      KAFKA_LOG_RETENTION_HOURS: 24
#      KAFKA_MESSAGE_MAX_BYTES: 10485760  # 100MB
#      KAFKA_REPLICA_FETCH_MAX_BYTES: 10485760  # 100MB
#      KAFKA_TOPIC_MAX_MESSAGE_BYTES: 104857600  # 100MB

  node:
    build:
      context: .
      dockerfile: ./contrib/node/Dockerfile
    ports:
      - "18332:18332"
      - "18444:18444"
    volumes:
    - bitcoin_data:/root/.electrumsv-node

  mysql:
    build:
      context: .
      dockerfile: ./contrib/mariadb/Dockerfile
    ports:
      - "52525:3306"
    environment:
      MYSQL_ROOT_PASSWORD: conduitpass
      MYSQL_DATABASE: conduitdb
      MYSQL_USER: conduitadmin
      MYSQL_PASSWORD: conduitpass


volumes:
  bitcoin_data:
