version: "3.8"

# This docker-compose is not for production use. It is solely for development and testing.

services:

  node:
    container_name: node
    build:
      context: .
      dockerfile: ./contrib/node/Dockerfile
    ports:
      - "18332:18332"
      - "18444:18444"
    volumes:
    - bitcoin_data:/root/.electrumsv-node

  mysql:
    build:
      context: .
      dockerfile: ./contrib/mariadb/Dockerfile
    ports:
      - "52525:3306"
    environment:
      MYSQL_ROOT_PASSWORD: conduitpass
      MYSQL_DATABASE: conduitdb
      MYSQL_USER: conduitadmin
      MYSQL_PASSWORD: conduitpass

  reference_server:
    container_name: reference_server
    depends_on:
      - "conduit-raw"
      - "conduit-index"
    build:
      context: .
      dockerfile: ./contrib/reference_server/Dockerfile
    ports:
      - "47124:47124"
      - "47126:47126"
    environment:
      SKIP_DOTENV_FILE: 1  # Allows us to overrride all of the defaults in the .env file
      EXTERNAL_HOST: "0.0.0.0"
      EXTERNAL_PORT: 47124
      INTERNAL_HOST: "0.0.0.0"
      INTERNAL_PORT: 47126
      EXPOSE_HEADER_SV_APIS: 1
      HEADER_SV_URL: 'http://host.docker.internal:34525'
      EXPOSE_PAYMAIL_APIS: 1
      EXPOSE_INDEXER_APIS: 1
      INDEXER_URL: 'http://host.docker.internal:34525'
      NOTIFICATION_TEXT_NEW_MESSAGE: New message arrived
      MAX_MESSAGE_CONTENT_LENGTH: 65536
      CHUNKED_BUFFER_SIZE: 1024
      NETWORK: regtest
      ENABLE_OUTBOUND_DATA_DELIVERY: 1
    command:
      sh -c 'python3 /reference_server/server.py'

  conduit-raw:
    build:
      context: .
      dockerfile: ./conduit_raw/Dockerfile
    ports:
      - "50000:50000"
      - "34525:34525"
      - "51495:51495"
      - "60000:60000"
      - "60001:60001"
      - "60002:60002"
      - "60003:60003"
    depends_on:
      - node
      - mysql
    environment:
      - IPC_SOCKET_SERVER_HOST=0.0.0.0:50000
      - BITCOIN_HOST=node
      - BITCOIN_RPC_PORT=18332
      - LMDB_READONLY=0
      - LMDB_DATABASE_PATH=/opt/lmdb_data
    working_dir: /opt
    command: sh -c 'python3 /opt/conduit_raw/run_conduit_raw.py'

  conduit-index:
    build:
      context: .
      dockerfile: ./conduit_index/Dockerfile
    depends_on:
      - node
      - mysql
      - conduit-raw
    environment:
      - IPC_SOCKET_SERVER_HOST=conduit-raw:50000
    working_dir: /opt
    command: sh -c 'python3 /opt/conduit_index/run_conduit_index.py'
#    command: sh -c 'gdb -ex r --args python3 /opt/conduit_index/run_conduit_index.py'


volumes:
  bitcoin_data:
