version: "3.8"

services:

  conduit-raw:
    build:
      context: .
      dockerfile: ./conduit_raw/Dockerfile
    ports:
      - "50000:50000"
    depends_on:
      - zookeeper
      - kafka
      - node
    volumes:
      - lmdb_data:/opt/lmdb_data
    environment:
      - LMDB_READONLY=0
      - LMDB_DATABASE_PATH=/opt/lmdb_data
    working_dir: /opt
    command: sh -c 'python3 /opt/conduit_raw/conduit_server.py --reset --regtest --node-host=node:18444 --kafka-host=kafka:9092'

  conduit-index:
    build:
      context: .
      dockerfile: ./conduit_index/Dockerfile
    depends_on:
      - node
      - mysql
      - zookeeper
      - kafka
    volumes:
      - lmdb_data:/opt/lmdb_data
    environment:
      - LMDB_READONLY=1
      - LMDB_DATABASE_PATH=/opt/lmdb_data
      # - CONDUIT_RAW_API_HOST=conduit-raw-api:80
    working_dir: /opt
    command: sh -c 'python3 /opt/conduit_index/conduit_server.py --reset --regtest --node-host=node:18444 --mysql-host=mysql:3306 --kafka-host=kafka:9092'


volumes:
  lmdb_data:
