version: "3.8"

services:

  zookeeper:
    image: zookeeper:3.4.14
    expose:
      - "2181"

  kafka:
    image: wurstmeister/kafka:2.13-2.6.0
    hostname: kafka
    ports:
      - "26638:26638"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:26638
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:26638
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "logging:1:1"
#      KAFKA_LOG_RETENTION_MINUTES: 100
      KAFKA_MESSAGE_MAX_BYTES: 10485760  # 100MB
      KAFKA_REPLICA_FETCH_MAX_BYTES: 10485760  # 100MB
      KAFKA_TOPIC_MAX_MESSAGE_BYTES: 104857600  # 100MB

  mysql:
    build:
      context: .
      dockerfile: ./contrib/mariadb/Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: conduitpass
      MYSQL_DATABASE: conduitdb
      MYSQL_USER: conduitadmin
      MYSQL_PASSWORD: conduitpass
    volumes:
      - ./contrib/mariadb/config:/etc/mysql/conf.d

#  scylla-node1:
#    image: scylladb/scylla:4.4.0
#    restart: always
#    command: --seeds=scylla-node1 --api-address 0.0.0.0
#    volumes:
#      - "./scylla.yaml:/etc/scylla/scylla.yaml"
#      - "./cassandra-rackdc.properties.dc1:/etc/scylla/cassandra-rackdc.properties"
#    ports:
#      - "9042:9042"

  # Hopefully part of the issue here is that the -preload option is not set
  node:
    build:
      context: .
      dockerfile: ./contrib/node/Dockerfile
    ports:
      - "18332:18332"
      - "18444:18444"
    environment:
      - NODE_RPCALLOWIP=0.0.0.0/0
      - NODE_RPCBIND=0.0.0.0
      - NODE_PORT=18332
      - NODE_P2P_PORT=18444
      - NODE_ZMQ_PORT=28332

  conduit-raw:
    build:
      context: .
      dockerfile: ./conduit_raw/Dockerfile
    ports:
      - "50000:50000"
    depends_on:
      - zookeeper
      - kafka
    working_dir: /opt
    command: sh -c 'python3 /opt/conduit_raw/conduit_server.py --regtest --node-host=node:18444'

  conduit-index:
    build:
      context: .
      dockerfile: ./conduit_index/Dockerfile
    depends_on:
      - zookeeper
      - kafka
      - node
      - mysql
    working_dir: /opt
    command: sh -c 'sleep 10 && python3 /opt/conduit_index/conduit_server.py --regtest --node-host=node:18444 --mysql-host=mysql:3306'
