version: "3.8"

services:

  conduit-raw:
    build:
      context: .
      dockerfile: ./conduit_raw/Dockerfile
    ports:
      - "50000:50000"
      - "34525:34525"
    depends_on:
      - node
    environment:
      - CONDUIT_RAW_API_HOST=0.0.0.0:50000
      - BITCOIN_HOST=node
      - BITCOIN_RPC_PORT=18332
      - LMDB_READONLY=0
      - LMDB_DATABASE_PATH=/opt/lmdb_data
    working_dir: /opt
    # Note - node-host=172.17.0.1:8333 (accesses a bare metal node on linux but leads to "Bad
    # Address" errors after a short time and I don't know why... So on linux platform, our hand
    # is currently forced to deploy to production bare metal!
    command: sh -c 'python3 /opt/conduit_raw/conduit_server.py --reset --regtest --node-host=node:18444 --mysql-host=mysql:3306'

  conduit-index:
    build:
      context: .
      dockerfile: ./conduit_index/Dockerfile
    depends_on:
      - node
      - mysql
      - conduit-raw
    environment:
      - CONDUIT_RAW_API_HOST=conduit-raw:50000
      - CONDUIT_INDEX_HOST=conduit-index
    working_dir: /opt
    # Note - node-host=172.17.0.1:8333 (accesses a bare metal node on linux but leads to "Bad
    # Address" errors after a short time and I don't know why... So on linux platform, our hand
    # is currently forced to deploy to production bare metal!
    command: sh -c 'python3 /opt/conduit_index/conduit_server.py --regtest --node-host=node:18444 --mysql-host=mysql:3306'
#    command: sh -c 'gdb -ex r --args python3 /opt/conduit_index/conduit_server.py --reset --regtest --node-host=node:18444 --mysql-host=mysql:3306 --kafka-host=kafka:9092'
