version: "3.8"

# This is for use assuming that API.REST is being developed and debugged in Visual Studio.

services:

  zookeeper:
    image: zookeeper:3.4.14
    expose:
      - "2181"

  kafka:
    image: wurstmeister/kafka:2.13-2.6.0
    hostname: kafka
    ports:
      - "26638:26638"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:26638
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:26638
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "logging:1:1,conduit-raw-headers-state:10:1"
      KAFKA_LOG_RETENTION_HOURS: 24
      KAFKA_MESSAGE_MAX_BYTES: 10485760  # 100MB
      KAFKA_REPLICA_FETCH_MAX_BYTES: 10485760  # 100MB
      KAFKA_TOPIC_MAX_MESSAGE_BYTES: 104857600  # 100MB

  node:
    build:
      context: .
      dockerfile: ./contrib/node/Dockerfile
    ports:
      - "18332:18332"
      - "18444:18444"
    volumes:
    - ./data/bitcoin_data:/root/.electrumsv-node
    environment:
      - NODE_RPCALLOWIP=0.0.0.0/0
      - NODE_RPCBIND=0.0.0.0
      - NODE_PORT=18332
      - NODE_P2P_PORT=18444
      - NODE_ZMQ_PORT=28332

  mysql:
    build:
      context: .
      dockerfile: ./contrib/mariadb/Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: conduitpass
      MYSQL_DATABASE: conduitdb
      MYSQL_USER: conduitadmin
      MYSQL_PASSWORD: conduitpass
    volumes:
      - ./contrib/mariadb/config/my.cnf:/etc/mysql/my.cnf

  conduit-raw:
    build:
      context: .
      dockerfile: ./conduit_raw/Dockerfile
    ports:
      - "50000:50000"
    depends_on:
      - zookeeper
      - kafka
      - node
    volumes:
      - lmdb_data:/opt/lmdb_data
    environment:
      - LMDB_READONLY=0
      - LMDB_DATABASE_PATH=/opt/lmdb_data
    working_dir: /opt
    command: sh -c 'python3 /opt/conduit_raw/conduit_server.py --reset --regtest --node-host=node:18444 --kafka-host=kafka:9092'

  conduit-index:
    build:
      context: .
      dockerfile: ./conduit_index/Dockerfile
    depends_on:
      - node
      - mysql
      - zookeeper
      - kafka
    volumes:
      - lmdb_data:/opt/lmdb_data
    environment:
      - LMDB_READONLY=1
      - LMDB_DATABASE_PATH=/opt/lmdb_data
      - CONDUIT_RAW_API_HOST=conduit-raw-api:80
    working_dir: /opt
    command: sh -c 'python3 /opt/conduit_index/conduit_server.py --reset --regtest --node-host=node:18444 --mysql-host=mysql:3306 --kafka-host=kafka:9092'

  spvchannels-db:
    container_name: spvchannels-db
    image: bitcoinsv/spvchannels-db:1.0.0
    volumes:
      - spvchannels-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: WR6NUJEyG-kYMKz9Z6Y9^%^SP^3kuX
      POSTGRES_DB: spvchannels
    networks:
      - spvchannels-network

  spvchannels-api:
    container_name: spvchannels
    image: electrumsv/spvchannels:1.1.0
    command: -startup
    ports:
      - "25009:25009"
    links:
      - spvchannels-db:spvchannels-db
    depends_on:
      - spvchannels-db
    volumes:
      - ./config/:/config/:ro
    environment:
      - AppConfiguration:DBConnectionString=Server=spvchannels-db;Port=5432;User Id=channels;Password=channels;Database=channels;
      - AppConfiguration:DBConnectionStringDDL=Server=spvchannels-db;Port=5432;User Id=channelsddl;Password=channels;Database=channels;
      - AppConfiguration:DBConnectionStringMaster=Server=spvchannels-db;Port=5432;User Id=postgres;Password=WR6NUJEyG-kYMKz9Z6Y9^%^SP^3kuX;Database=channels;
      - AppConfiguration:NotificationTextNewMessage=New message arrived.
      - AppConfiguration:MaxMessageContentLength=65536
      - AppConfiguration:ChunkedBufferSize=1024
      - AppConfiguration:TokenSize=64
      - AppConfiguration:CacheSize=1048576
      - AppConfiguration:CacheSlidingExpirationTime=60
      - AppConfiguration:CacheAbsoluteExpirationTime=600
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_NPGSQLLOGMANAGER=False
      - ASPNETCORE_URLS=http://+:25009
    networks:
      - spvchannels-network


volumes:
  spvchannels-volume:
  lmdb_data:

networks:
  spvchannels-network:
