# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: conduit_raw.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='conduit_raw.proto',
  package='conduit_raw',
  syntax='proto3',
  serialized_options=b'\252\002\nConduitRaw',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x63onduit_raw.proto\x12\x0b\x63onduit_raw\"\x1b\n\x0bPingRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\x1f\n\x0cPingResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1e\n\x0bStopRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x0cStopResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\'\n\x12\x42lockNumberRequest\x12\x11\n\tblockHash\x18\x01 \x01(\x0c\"*\n\x13\x42lockNumberResponse\x12\x13\n\x0b\x62lockNumber\x18\x01 \x01(\x04\"#\n\x0c\x42lockRequest\x12\x13\n\x0b\x62lockNumber\x18\x01 \x01(\r\"!\n\rBlockResponse\x12\x10\n\x08rawBlock\x18\x01 \x01(\x0c\"8\n\x14MerkleTreeRowRequest\x12\x11\n\tblockHash\x18\x01 \x01(\x0c\x12\r\n\x05level\x18\x02 \x01(\r\")\n\x15MerkleTreeRowResponse\x12\x10\n\x08mtreeRow\x18\x01 \x01(\x0c\".\n\x19TransactionOffsetsRequest\x12\x11\n\tblockHash\x18\x01 \x01(\x0c\"4\n\x1aTransactionOffsetsResponse\x12\x16\n\x0etxOffsetsArray\x18\x01 \x03(\x04\")\n\x14\x42lockMetadataRequest\x12\x11\n\tblockHash\x18\x01 \x01(\x0c\"/\n\x15\x42lockMetadataResponse\x12\x16\n\x0e\x62lockSizeBytes\x18\x01 \x01(\x04\x32\xbe\x04\n\nConduitRaw\x12;\n\x04Ping\x12\x18.conduit_raw.PingRequest\x1a\x19.conduit_raw.PingResponse\x12;\n\x04Stop\x12\x18.conduit_raw.StopRequest\x1a\x19.conduit_raw.StopResponse\x12S\n\x0eGetBlockNumber\x12\x1f.conduit_raw.BlockNumberRequest\x1a .conduit_raw.BlockNumberResponse\x12\x41\n\x08GetBlock\x12\x19.conduit_raw.BlockRequest\x1a\x1a.conduit_raw.BlockResponse\x12Y\n\x10GetMerkleTreeRow\x12!.conduit_raw.MerkleTreeRowRequest\x1a\".conduit_raw.MerkleTreeRowResponse\x12h\n\x15GetTransactionOffsets\x12&.conduit_raw.TransactionOffsetsRequest\x1a\'.conduit_raw.TransactionOffsetsResponse\x12Y\n\x10GetBlockMetadata\x12!.conduit_raw.BlockMetadataRequest\x1a\".conduit_raw.BlockMetadataResponseB\r\xaa\x02\nConduitRawb\x06proto3'
)




_PINGREQUEST = _descriptor.Descriptor(
  name='PingRequest',
  full_name='conduit_raw.PingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='conduit_raw.PingRequest.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=61,
)


_PINGRESPONSE = _descriptor.Descriptor(
  name='PingResponse',
  full_name='conduit_raw.PingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='conduit_raw.PingResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=94,
)


_STOPREQUEST = _descriptor.Descriptor(
  name='StopRequest',
  full_name='conduit_raw.StopRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='conduit_raw.StopRequest.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=126,
)


_STOPRESPONSE = _descriptor.Descriptor(
  name='StopResponse',
  full_name='conduit_raw.StopResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='conduit_raw.StopResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=159,
)


_BLOCKNUMBERREQUEST = _descriptor.Descriptor(
  name='BlockNumberRequest',
  full_name='conduit_raw.BlockNumberRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='blockHash', full_name='conduit_raw.BlockNumberRequest.blockHash', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=200,
)


_BLOCKNUMBERRESPONSE = _descriptor.Descriptor(
  name='BlockNumberResponse',
  full_name='conduit_raw.BlockNumberResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='blockNumber', full_name='conduit_raw.BlockNumberResponse.blockNumber', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=244,
)


_BLOCKREQUEST = _descriptor.Descriptor(
  name='BlockRequest',
  full_name='conduit_raw.BlockRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='blockNumber', full_name='conduit_raw.BlockRequest.blockNumber', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=281,
)


_BLOCKRESPONSE = _descriptor.Descriptor(
  name='BlockResponse',
  full_name='conduit_raw.BlockResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rawBlock', full_name='conduit_raw.BlockResponse.rawBlock', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=283,
  serialized_end=316,
)


_MERKLETREEROWREQUEST = _descriptor.Descriptor(
  name='MerkleTreeRowRequest',
  full_name='conduit_raw.MerkleTreeRowRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='blockHash', full_name='conduit_raw.MerkleTreeRowRequest.blockHash', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='level', full_name='conduit_raw.MerkleTreeRowRequest.level', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=318,
  serialized_end=374,
)


_MERKLETREEROWRESPONSE = _descriptor.Descriptor(
  name='MerkleTreeRowResponse',
  full_name='conduit_raw.MerkleTreeRowResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mtreeRow', full_name='conduit_raw.MerkleTreeRowResponse.mtreeRow', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=376,
  serialized_end=417,
)


_TRANSACTIONOFFSETSREQUEST = _descriptor.Descriptor(
  name='TransactionOffsetsRequest',
  full_name='conduit_raw.TransactionOffsetsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='blockHash', full_name='conduit_raw.TransactionOffsetsRequest.blockHash', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=419,
  serialized_end=465,
)


_TRANSACTIONOFFSETSRESPONSE = _descriptor.Descriptor(
  name='TransactionOffsetsResponse',
  full_name='conduit_raw.TransactionOffsetsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='txOffsetsArray', full_name='conduit_raw.TransactionOffsetsResponse.txOffsetsArray', index=0,
      number=1, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=467,
  serialized_end=519,
)


_BLOCKMETADATAREQUEST = _descriptor.Descriptor(
  name='BlockMetadataRequest',
  full_name='conduit_raw.BlockMetadataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='blockHash', full_name='conduit_raw.BlockMetadataRequest.blockHash', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=521,
  serialized_end=562,
)


_BLOCKMETADATARESPONSE = _descriptor.Descriptor(
  name='BlockMetadataResponse',
  full_name='conduit_raw.BlockMetadataResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='blockSizeBytes', full_name='conduit_raw.BlockMetadataResponse.blockSizeBytes', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=564,
  serialized_end=611,
)

DESCRIPTOR.message_types_by_name['PingRequest'] = _PINGREQUEST
DESCRIPTOR.message_types_by_name['PingResponse'] = _PINGRESPONSE
DESCRIPTOR.message_types_by_name['StopRequest'] = _STOPREQUEST
DESCRIPTOR.message_types_by_name['StopResponse'] = _STOPRESPONSE
DESCRIPTOR.message_types_by_name['BlockNumberRequest'] = _BLOCKNUMBERREQUEST
DESCRIPTOR.message_types_by_name['BlockNumberResponse'] = _BLOCKNUMBERRESPONSE
DESCRIPTOR.message_types_by_name['BlockRequest'] = _BLOCKREQUEST
DESCRIPTOR.message_types_by_name['BlockResponse'] = _BLOCKRESPONSE
DESCRIPTOR.message_types_by_name['MerkleTreeRowRequest'] = _MERKLETREEROWREQUEST
DESCRIPTOR.message_types_by_name['MerkleTreeRowResponse'] = _MERKLETREEROWRESPONSE
DESCRIPTOR.message_types_by_name['TransactionOffsetsRequest'] = _TRANSACTIONOFFSETSREQUEST
DESCRIPTOR.message_types_by_name['TransactionOffsetsResponse'] = _TRANSACTIONOFFSETSRESPONSE
DESCRIPTOR.message_types_by_name['BlockMetadataRequest'] = _BLOCKMETADATAREQUEST
DESCRIPTOR.message_types_by_name['BlockMetadataResponse'] = _BLOCKMETADATARESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PingRequest = _reflection.GeneratedProtocolMessageType('PingRequest', (_message.Message,), {
  'DESCRIPTOR' : _PINGREQUEST,
  '__module__' : 'conduit_raw_pb2'
  # @@protoc_insertion_point(class_scope:conduit_raw.PingRequest)
  })
_sym_db.RegisterMessage(PingRequest)

PingResponse = _reflection.GeneratedProtocolMessageType('PingResponse', (_message.Message,), {
  'DESCRIPTOR' : _PINGRESPONSE,
  '__module__' : 'conduit_raw_pb2'
  # @@protoc_insertion_point(class_scope:conduit_raw.PingResponse)
  })
_sym_db.RegisterMessage(PingResponse)

StopRequest = _reflection.GeneratedProtocolMessageType('StopRequest', (_message.Message,), {
  'DESCRIPTOR' : _STOPREQUEST,
  '__module__' : 'conduit_raw_pb2'
  # @@protoc_insertion_point(class_scope:conduit_raw.StopRequest)
  })
_sym_db.RegisterMessage(StopRequest)

StopResponse = _reflection.GeneratedProtocolMessageType('StopResponse', (_message.Message,), {
  'DESCRIPTOR' : _STOPRESPONSE,
  '__module__' : 'conduit_raw_pb2'
  # @@protoc_insertion_point(class_scope:conduit_raw.StopResponse)
  })
_sym_db.RegisterMessage(StopResponse)

BlockNumberRequest = _reflection.GeneratedProtocolMessageType('BlockNumberRequest', (_message.Message,), {
  'DESCRIPTOR' : _BLOCKNUMBERREQUEST,
  '__module__' : 'conduit_raw_pb2'
  # @@protoc_insertion_point(class_scope:conduit_raw.BlockNumberRequest)
  })
_sym_db.RegisterMessage(BlockNumberRequest)

BlockNumberResponse = _reflection.GeneratedProtocolMessageType('BlockNumberResponse', (_message.Message,), {
  'DESCRIPTOR' : _BLOCKNUMBERRESPONSE,
  '__module__' : 'conduit_raw_pb2'
  # @@protoc_insertion_point(class_scope:conduit_raw.BlockNumberResponse)
  })
_sym_db.RegisterMessage(BlockNumberResponse)

BlockRequest = _reflection.GeneratedProtocolMessageType('BlockRequest', (_message.Message,), {
  'DESCRIPTOR' : _BLOCKREQUEST,
  '__module__' : 'conduit_raw_pb2'
  # @@protoc_insertion_point(class_scope:conduit_raw.BlockRequest)
  })
_sym_db.RegisterMessage(BlockRequest)

BlockResponse = _reflection.GeneratedProtocolMessageType('BlockResponse', (_message.Message,), {
  'DESCRIPTOR' : _BLOCKRESPONSE,
  '__module__' : 'conduit_raw_pb2'
  # @@protoc_insertion_point(class_scope:conduit_raw.BlockResponse)
  })
_sym_db.RegisterMessage(BlockResponse)

MerkleTreeRowRequest = _reflection.GeneratedProtocolMessageType('MerkleTreeRowRequest', (_message.Message,), {
  'DESCRIPTOR' : _MERKLETREEROWREQUEST,
  '__module__' : 'conduit_raw_pb2'
  # @@protoc_insertion_point(class_scope:conduit_raw.MerkleTreeRowRequest)
  })
_sym_db.RegisterMessage(MerkleTreeRowRequest)

MerkleTreeRowResponse = _reflection.GeneratedProtocolMessageType('MerkleTreeRowResponse', (_message.Message,), {
  'DESCRIPTOR' : _MERKLETREEROWRESPONSE,
  '__module__' : 'conduit_raw_pb2'
  # @@protoc_insertion_point(class_scope:conduit_raw.MerkleTreeRowResponse)
  })
_sym_db.RegisterMessage(MerkleTreeRowResponse)

TransactionOffsetsRequest = _reflection.GeneratedProtocolMessageType('TransactionOffsetsRequest', (_message.Message,), {
  'DESCRIPTOR' : _TRANSACTIONOFFSETSREQUEST,
  '__module__' : 'conduit_raw_pb2'
  # @@protoc_insertion_point(class_scope:conduit_raw.TransactionOffsetsRequest)
  })
_sym_db.RegisterMessage(TransactionOffsetsRequest)

TransactionOffsetsResponse = _reflection.GeneratedProtocolMessageType('TransactionOffsetsResponse', (_message.Message,), {
  'DESCRIPTOR' : _TRANSACTIONOFFSETSRESPONSE,
  '__module__' : 'conduit_raw_pb2'
  # @@protoc_insertion_point(class_scope:conduit_raw.TransactionOffsetsResponse)
  })
_sym_db.RegisterMessage(TransactionOffsetsResponse)

BlockMetadataRequest = _reflection.GeneratedProtocolMessageType('BlockMetadataRequest', (_message.Message,), {
  'DESCRIPTOR' : _BLOCKMETADATAREQUEST,
  '__module__' : 'conduit_raw_pb2'
  # @@protoc_insertion_point(class_scope:conduit_raw.BlockMetadataRequest)
  })
_sym_db.RegisterMessage(BlockMetadataRequest)

BlockMetadataResponse = _reflection.GeneratedProtocolMessageType('BlockMetadataResponse', (_message.Message,), {
  'DESCRIPTOR' : _BLOCKMETADATARESPONSE,
  '__module__' : 'conduit_raw_pb2'
  # @@protoc_insertion_point(class_scope:conduit_raw.BlockMetadataResponse)
  })
_sym_db.RegisterMessage(BlockMetadataResponse)


DESCRIPTOR._options = None

_CONDUITRAW = _descriptor.ServiceDescriptor(
  name='ConduitRaw',
  full_name='conduit_raw.ConduitRaw',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=614,
  serialized_end=1188,
  methods=[
  _descriptor.MethodDescriptor(
    name='Ping',
    full_name='conduit_raw.ConduitRaw.Ping',
    index=0,
    containing_service=None,
    input_type=_PINGREQUEST,
    output_type=_PINGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Stop',
    full_name='conduit_raw.ConduitRaw.Stop',
    index=1,
    containing_service=None,
    input_type=_STOPREQUEST,
    output_type=_STOPRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetBlockNumber',
    full_name='conduit_raw.ConduitRaw.GetBlockNumber',
    index=2,
    containing_service=None,
    input_type=_BLOCKNUMBERREQUEST,
    output_type=_BLOCKNUMBERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetBlock',
    full_name='conduit_raw.ConduitRaw.GetBlock',
    index=3,
    containing_service=None,
    input_type=_BLOCKREQUEST,
    output_type=_BLOCKRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetMerkleTreeRow',
    full_name='conduit_raw.ConduitRaw.GetMerkleTreeRow',
    index=4,
    containing_service=None,
    input_type=_MERKLETREEROWREQUEST,
    output_type=_MERKLETREEROWRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetTransactionOffsets',
    full_name='conduit_raw.ConduitRaw.GetTransactionOffsets',
    index=5,
    containing_service=None,
    input_type=_TRANSACTIONOFFSETSREQUEST,
    output_type=_TRANSACTIONOFFSETSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetBlockMetadata',
    full_name='conduit_raw.ConduitRaw.GetBlockMetadata',
    index=6,
    containing_service=None,
    input_type=_BLOCKMETADATAREQUEST,
    output_type=_BLOCKMETADATARESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONDUITRAW)

DESCRIPTOR.services_by_name['ConduitRaw'] = _CONDUITRAW

# @@protoc_insertion_point(module_scope)
